-- Database Schema for AI Twitter Agent

-- Table: tweets
CREATE TABLE IF NOT EXISTS tweets (
    tweet_id TEXT PRIMARY KEY UNIQUE,
    username TEXT NOT NULL,
    text TEXT NOT NULL,
    likes INTEGER DEFAULT 0,
    followers INTEGER DEFAULT 0,
    tweet_url TEXT,
    scored BOOLEAN DEFAULT FALSE,
    should_reply BOOLEAN DEFAULT FALSE,
    engagement_score INTEGER DEFAULT 0,
    tweet_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: reply_queue
CREATE TABLE IF NOT EXISTS reply_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tweet_id TEXT REFERENCES tweets(tweet_id),
    username TEXT NOT NULL,
    reply_text TEXT NOT NULL,
    status TEXT CHECK (status IN ('pending', 'posted', 'failed')) DEFAULT 'pending',
    scheduled_for TIMESTAMP WITH TIME ZONE,
    posted_at TIMESTAMP WITH TIME ZONE
);

-- Table: conversations (Memory)
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    tweet_id TEXT NOT NULL,
    our_reply TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: bot_limits (Anti-Ban)
CREATE TABLE IF NOT EXISTS bot_limits (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    replies_today INTEGER DEFAULT 0,
    last_reply_time TIMESTAMP WITH TIME ZONE
);

-- Initialize bot_limits if not exists
INSERT INTO bot_limits (id, replies_today, last_reply_time)
VALUES (1, 0, NOW())
ON CONFLICT (id) DO NOTHING;
